# Generated by Django 4.2.10 on 2026-02-28 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clerk_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tokenblacklist',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='TokenBlacklist',
        ),
        migrations.AddIndex(
            model_name='clerkuser',
            index=models.Index(fields=['clerk_user_id'], name='clerk_users_clerk_u_d5c388_idx'),
        ),
        migrations.AddIndex(
            model_name='clerkuser',
            index=models.Index(fields=['email'], name='clerk_users_email_91e2ee_idx'),
        ),
    ]
