# Generated by Django 4.2.10 on 2026-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('nationalId', 'National ID'), ('drivingLicense', 'Driving License'), ('passport', 'Passport'), ('other', 'Other')], max_length=50),
        ),
    ]
