# Generated by Django 4.2.10 on 2026-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_document_file_document_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='online_link',
            field=models.URLField(blank=True, help_text='Online registration/application link', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='steps',
            field=models.JSONField(default=list, help_text='List of process steps'),
        ),
        migrations.RunSQL(
            "UPDATE core_service SET required_documents = '[]' WHERE required_documents =  ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='service',
            name='required_documents',
            field=models.JSONField(default=list, help_text='List of required documents'),
        ),
    ]
